import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { randomUUID } from 'node:crypto';
import { createApp } from '../src/app.js';
import { applicationFor } from './fixtures.js';
import { recentMail } from '../src/mail.js';
import { normalizeDemoPhone } from '../src/demoPayments.js';
import { quoteFee } from '../../shared/fees.js';
process.env.NODE_ENV='development';process.env.DEMO_PAYMENTS_ENABLED='1';process.env.MAIL_PROVIDER='off';process.env.RECAPTCHA_SITE_KEY='';process.env.FIREBASE_PROJECT_ID='';
process.env.ADMIN_EMAIL='immediate-admin@veyra.test';process.env.ADMIN_PASSWORD='Immediate-Admin-Test-2026!';
const {app,db}=createApp(':memory:');const server=createServer(app);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
const api=async(method:string,path:string,token?:string,body?:unknown)=>{const r=await fetch(base+path,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,json:await r.json() as any};};
let checks=0;function check(name:string,ok:unknown){assert.ok(ok,name);checks++;console.log(`✓ ${name}`);}
try{
 const admin=(await api('POST','/api/auth/login',undefined,{email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD})).json.token;
 async function member(name:string,phone:string,type:'personal'|'business'='personal') {const r=await api('POST','/api/auth/register',undefined,{name,email:`${name}@veyra.test`,password:'Immediate-Member-Test-2026!',accountType:type,business:type==='business'?'Demo Co.':'',profile:{...applicationFor(type,name,'Demo Co.'),phone}});assert.equal(r.status,201);await api('POST',`/api/admin/kyc/${r.json.user.id}/decision`,admin,{decision:'approved'});return {id:r.json.user.id,email:r.json.user.email,token:r.json.token,phone};}
 const a=await member('Alice','+1 555 010 1011'),b=await member('Bob','+1 555 010 1012'),c=await member('Business','+234 803 123 4567','business');
 const balance=(id=a.id)=>(db.prepare('SELECT balance_cents FROM accounts WHERE user_id=?').get(id) as {balance_cents:number}).balance_cents;
 const funding=async(token=a.token)=>(await api('GET','/api/me/funding',token)).json;
 const deposit=(body:unknown,token=a.token)=>api('POST','/api/me/deposits',token,body);
 const action=(body:unknown,token=a.token)=>api('POST','/api/me/demo-payments/action',token,body);
 const inboxBefore=recentMail.length;
 check('funding requires authentication',(await api('GET','/api/me/funding')).status===401);
 check('deposit requires authentication',(await api('POST','/api/me/deposits',undefined,{})).status===401);
 db.prepare("INSERT INTO external_accounts(id,user_id,bank_name,account_name,last4,account_type,status,provider_reference,created_at,updated_at) VALUES(?,?,'Linked bank','Personal checking','1234','Checking','verified','fixture-link',1,1)").run('fixture-link',a.id);
 db.prepare("INSERT INTO external_accounts(id,user_id,kind,bank_name,account_name,last4,account_type,card_brand,card_exp_month,card_exp_year,billing_address_json,status,provider_reference,created_at,updated_at,verification_kind,verification_note,request_key) VALUES('fixture-card',?,'card','Visa','Alice debit card','4242','Checking','Visa',12,2030,'{}','verified','card-token:fixture-card',1,1,'card_token','fixture card reference',NULL)").run(a.id);
 db.prepare("UPDATE accounts SET receiving_details_configured=1 WHERE user_id=?").run(a.id);
 const sources=(await funding()).methods;check('all nine methods have mock sources (ACH also receives into the admin-set Veyra account)',sources.length===9&&(await funding()).demoMode);
 for(const m of sources){const before=balance(),body={methodId:m.id,amount:'25.01',requestKey:randomUUID(),note:'',demo:true};
  const depositFee=quoteFee(m.kind==='card'?'card_deposit':'deposit',2501).feeCents, credit=2501-depositFee;
  const posted=await deposit(body);check(`${m.kind}: immediately confirmed`,posted.status===201&&posted.json.request.status==='confirmed'&&posted.json.fee===(depositFee/100).toFixed(2));
  check(`${m.kind}: credits normal account immediately`,balance()===before+credit);
  await Promise.all([deposit(body),deposit(body)]);check(`${m.kind}: retries never double-credit`,balance()===before+credit);
  check(`${m.kind}: one cleared ledger record`,(db.prepare('SELECT COUNT(*) AS n FROM transactions WHERE reference=?').get(posted.json.request.reference) as any).n===1);
  check(`${m.kind}: changed replay refused`,(await deposit({...body,amount:'26.01'})).status===400);
 }
 check('separate wallet not created',(db.prepare('SELECT COUNT(*) AS n FROM demo_wallets').get() as any).n===0);
 check('no pending approval steps',(await funding()).requests.every((r:any)=>r.status==='confirmed'));
 const body={methodId:sources[0].id,amount:'25',requestKey:randomUUID(),note:'',demo:true};
 check('explicit demo acknowledgement required',(await deposit({...body,demo:false})).status===400);
 check('cannot use another account source',(await deposit(body,b.token)).status===400);
 check('credentials rejected',(await deposit({...body,cardNumber:'4242424242424242'})).status===400);
 for(const amount of ['0','-1','9.99','100000.01','1.001','1e3',true,{}])check(`invalid amount ${JSON.stringify(amount)} rejected`,(await deposit({...body,amount,requestKey:randomUUID()})).status===400);
 check('invalid request key refused',(await deposit({...body,requestKey:'bad'})).status===400);
 check('staff cannot credit',(await deposit(body,admin)).status===403);
 db.prepare("UPDATE users SET status='restricted' WHERE id=?").run(a.id);check('restricted owner cannot credit',(await deposit(body)).status===403);db.prepare("UPDATE users SET status='active' WHERE id=?").run(a.id);
 db.prepare("UPDATE kyc_records SET review_state='submitted' WHERE user_id=?").run(a.id);check('unapproved owner cannot credit',(await deposit(body)).status===403);db.prepare("UPDATE kyc_records SET review_state='approved' WHERE user_id=?").run(a.id);
 db.prepare('UPDATE users SET team_owner_id=? WHERE id=?').run(a.id,c.id);check('team login cannot credit',(await deposit(body,c.token)).status!==201);db.prepare('UPDATE users SET team_owner_id=NULL WHERE id=?').run(c.id);
 const beforeLimit=balance(),requestsBefore=(await funding()).requests.length;db.prepare('UPDATE accounts SET balance_cents=1000000000 WHERE user_id=?').run(a.id);
 check('balance cap refused atomically',(await deposit(body)).status===400&&(await funding()).requests.length===requestsBefore);db.prepare('UPDATE accounts SET balance_cents=? WHERE user_id=?').run(beforeLimit,a.id);
 const snap=(await api('GET','/api/me/demo-payments',a.token)).json;check('QR contacts still use signup profile',snap.member.email===a.email&&snap.member.phone===a.phone);check('snapshot uses account balance',snap.balanceCents===balance());
 check('starter wallet endpoint retired',(await action({action:'start'})).status===400);
 const preview=(identifier=b.email,token=a.token,category='')=>action({action:'preview_transfer',identifier,method:'Zelle',amount:'10.25',category},token);
 const p=await preview();check('recipient resolves before sending',p.status===200&&p.json.preview.name==='Bob');
 const before=balance(),recipientBefore=balance(b.id),confirm={action:'confirm_transfer',id:p.json.preview.id,decision:'completed'};
 check('review has no debit',balance()===before);check('other user cannot confirm',(await action(confirm,b.token)).status===400);
 const paid=await action(confirm);await action(confirm);const transferFee=quoteFee('transfer',1025).feeCents;check('payment debits funded account once',paid.status===200&&balance()===before-1025-transferFee);check('recipient account credited once',balance(b.id)===recipientBefore+1025);check('receipt reflects normal account',paid.json.result.balanceAfter===balance()/100&&paid.json.result.fee===transferFee/100);
 check('phone resolves recipient',(await preview('5550101012')).json.preview.name==='Bob');check('international phone normalized',normalizeDemoPhone(c.phone)==='+2348031234567');check('self payment refused',(await preview(a.email)).status===400);
 db.prepare('UPDATE users SET phone=? WHERE id=?').run(b.phone,c.id);check('ambiguous phone refused',(await preview(b.phone)).status===400);db.prepare('UPDATE users SET phone=? WHERE id=?').run(c.phone,c.id);
 const stale=await preview();db.prepare("UPDATE users SET email='changed@veyra.test' WHERE id=?").run(b.id);check('recipient rechecked at commit',(await action({...confirm,id:stale.json.preview.id})).status===400);db.prepare('UPDATE users SET email=? WHERE id=?').run(b.email,b.id);
 const expired=await preview();db.prepare('UPDATE demo_account_payment_previews SET expires_at=0 WHERE id=?').run(expired.json.preview.id);check('expired review refused',(await action({...confirm,id:expired.json.preview.id})).status===400);
 const cap=await preview(),senderBefore=balance(),bobBefore=balance(b.id);db.prepare('UPDATE accounts SET balance_cents=1000000000 WHERE user_id=?').run(b.id);check('recipient cap rolls back sender debit',(await action({...confirm,id:cap.json.preview.id})).status===400&&balance()===senderBefore);db.prepare('UPDATE accounts SET balance_cents=? WHERE user_id=?').run(bobBefore,b.id);
 check('business requires category',(await preview(a.email,c.token)).status===400);check('business category accepted',(await preview(a.email,c.token,'Supplies')).status===200);
 check('no real emails emitted',recentMail.length===inboxBefore);
 process.env.DEMO_PAYMENTS_ENABLED='0';check('disabled mode refuses demo credit',(await deposit(body)).status===400);check('disabled fixtures not exposed',(await funding()).methods.length===0);check('disabled payments refused',(await action(confirm)).status===400);
 process.env.ACCOUNT_LEDGER_ENABLED='1';
 check('standard account switch enables immediate funding',(await funding()).immediateFunding===true);
 const canonicalBefore=balance(),canonical={methodId:sources[0].id,amount:'10.01',requestKey:randomUUID(),accountEntry:true};
 const canonicalReply=await deposit(canonical);
 check('canonical account-entry request credits the ordinary account',canonicalReply.status===201&&balance()===canonicalBefore+1001);
 check('new account credits use ordinary references and labels',canonicalReply.json.request.reference.startsWith('VYR-')&&!/demo/i.test(JSON.parse(canonicalReply.json.request.method_snapshot).label));
 await deposit(canonical);check('canonical account-entry replay remains idempotent',balance()===canonicalBefore+1001);
 process.env.ACCOUNT_LEDGER_ENABLED='0';process.env.DEMO_PAYMENTS_ENABLED='1';
 check('explicit account switch off wins over legacy switch',!(await funding()).immediateFunding);
 process.env.ACCOUNT_LEDGER_ENABLED='1';process.env.NODE_ENV='production';check('production refuses demo funding',(await deposit(body)).status===400);check('production refuses demo transfers',(await action(confirm)).status===400);
 console.log(`\n${checks} immediate funding and payment checks passed.`);
}finally{await new Promise<void>(r=>server.close(()=>r()));db.close();}
