import assert from "node:assert/strict";
import { createServer } from "node:http";
import { randomUUID, createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { createApp } from "../src/app.js";
import { applicationFor } from "./fixtures.js";
import { createPriceFixture } from "./price-fixture.js";
import { CRYPTO_ACTIVITIES, CRYPTO_STATUSES, cryptoNotificationContent, type CryptoNotification } from "../../shared/cryptoNotifications.js";
import { buildCryptoEmail } from "../../src/emails/crypto.js";
import { sendCryptoNotification } from "../src/cryptoNotifications.js";
import { ASSETS } from "../../shared/catalog.js";
import { assetIcon } from "../../shared/assetIcons.js";

Object.assign(process.env, { NODE_ENV: "development", ACCOUNT_LEDGER_ENABLED: "1", PREVIEW_CRYPTO_DATA: "0", CRYPTO_TRADING_ENABLED: "1", MAIL_PROVIDER: "off", ADMIN_EMAIL: "polish-admin@veyra.test", ADMIN_PASSWORD: "Polish-admin-2026!", RECAPTCHA_SITE_KEY: "", FIREBASE_PROJECT_ID: "" });
const prices = createPriceFixture(); await new Promise<void>(r => prices.listen(0, "127.0.0.1", r));
process.env.CRYPTO_PRICES_URL = `http://127.0.0.1:${(prices.address() as { port: number }).port}/prices`;
const { app, db } = createApp(":memory:"); const server = createServer(app); await new Promise<void>(r => server.listen(0, "127.0.0.1", r));
const base = `http://127.0.0.1:${(server.address() as { port: number }).port}`;
const api = async (method: string, path: string, token?: string, body?: unknown) => {
  const res = await fetch(base + path, { method, headers: { "content-type": "application/json", ...(token ? { authorization: `Bearer ${token}` } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
  return { status: res.status, body: await res.json() as any };
};
let checks = 0; const check = (label: string, ok: unknown) => { assert.ok(ok, label); checks++; console.log(`✓ ${label}`); };
try {
  const admin = (await api("POST", "/api/auth/login", undefined, { email: process.env.ADMIN_EMAIL, password: process.env.ADMIN_PASSWORD })).body.token;
  async function member(name: string) {
    const created = await api("POST", "/api/auth/register", undefined, { name, email: `${name}@veyra.test`, password: "Polish-member-2026!", accountType: "personal", business: "", profile: applicationFor("personal", name) });
    assert.equal(created.status, 201);
    await api("POST", `/api/admin/kyc/${created.body.user.id}/decision`, admin, { decision: "approved" });
    return { id: created.body.user.id, token: created.body.token };
  }
  const a = await member("Alice"), b = await member("Bob");
  const funding = async (token = a.token) => (await api("GET", "/api/me/funding", token)).body;
  const deposit = (methodId: string, key = randomUUID(), token = a.token) => api("POST", "/api/me/deposits", token, { methodId, amount: "25", accountEntry: true, requestKey: key, note: "" });
  check("external account reads require authentication", (await api("GET", "/api/me/external-accounts")).status === 401);
  const initial = await funding();
  check("new owner has no invented linked accounts or receiving details", initial.linkedAccounts.length === 0 && initial.directDeposit === null);
  check("unlinked ACH cannot credit an account", (await deposit(initial.methods.find((m: any) => m.kind === "ach").id)).status === 400);
  check("unconfigured payroll details cannot credit an account", (await deposit(initial.methods.find((m: any) => m.kind === "direct_deposit").id)).status === 400);
  const saved = await api("PATCH", `/api/admin/members/${a.id}/account-details`, admin, { accountNumber: "777000123456", routingNumber: "021000021", bankName: "Owner Specific Bank", bankAccountType: "Savings", accountType: "personal", business: "", reason: "Configure receiving details" });
  check("administrator configures this owner's banking information", saved.status === 200);
  const updated = await funding();
  check("Direct Deposit uses this owner's admin-configured details", updated.directDeposit.bank_name === "Owner Specific Bank" && updated.directDeposit.account_number === "777000123456" && updated.directDeposit.routing_number === "021000021" && updated.directDeposit.account_type === "Savings");
  check("another owner cannot see the configured receiving details", (await funding(b.token)).directDeposit === null);
  const insertLink = db.prepare("INSERT INTO external_accounts(id,user_id,bank_name,account_name,last4,account_type,status,provider_reference,created_at,updated_at) VALUES(?,?,'Connected Bank','Checking','7890','Checking',?,?,1,1)");
  insertLink.run("pending-link", a.id, "pending", null);
  insertLink.run("verified-link", a.id, "verified", "trusted-provider-reference");
  insertLink.run("bob-link", b.id, "verified", "other-owner-provider-reference");
  const linked = (await api("GET", "/api/me/external-accounts", a.token)).body;
  check("only the current owner's verified links are exposed", linked.accounts.length === 1 && linked.accounts[0].id === "verified-link" && !JSON.stringify(linked).includes("trusted-provider-reference"));
  const linkedMethod = (await funding()).methods.find((m: any) => m.linkedAccountId === "verified-link");
  check("verified bank appears in funding dropdown with masked account", linkedMethod.label.includes("Connected Bank") && linkedMethod.label.includes("7890"));
  check("foreign linked funding source is rejected", (await deposit(linkedMethod.id, randomUUID(), b.token)).status === 400);
  const key = randomUUID(); check("explicit internal credit with linked reference succeeds", (await deposit(linkedMethod.id, key)).status === 201);
  db.prepare("UPDATE external_accounts SET status='disconnected' WHERE id='verified-link'").run();
  check("completed credit still replays after disconnect", (await deposit(linkedMethod.id, key)).status === 201);
  check("disconnected account cannot fund a new request", (await deposit(linkedMethod.id)).status === 400);
  const bank = (await funding()).methods.find((m: any) => m.kind === "bank"); await deposit(bank.id);
  const notes = () => db.prepare("SELECT * FROM notifications WHERE user_id=? AND type='crypto'").all(a.id) as any[];
  async function trade(action: string, fromAsset: string, toAsset: string, amount: string) {
    const quote = await api("POST", "/api/me/crypto/quote", a.token, { action, fromAsset, toAsset, amount }); assert.equal(quote.status, 201, JSON.stringify(quote.body));
    const before = notes().length;
    const confirmed = await api("POST", "/api/me/crypto/confirm", a.token, { quoteId: quote.body.quote.id }); assert.equal(confirmed.status, 200);
    await api("POST", "/api/me/crypto/confirm", a.token, { quoteId: quote.body.quote.id });
    check(`${action} emits exactly one persisted completion notification across retries`, notes().length === before + 1 && notes().some(n => n.detail.includes(confirmed.body.receipt.reference)));
  }
  await trade("buy", "USD", "USDC", "20"); await trade("swap", "USDC", "SOL", "10"); await trade("sell", "USDC", "USD", "2");
  const quoted = await api("POST", "/api/me/crypto/quote", a.token, { action: "buy", fromAsset: "USD", toAsset: "USDC", amount: "1" });
  db.prepare("UPDATE crypto_orders SET expires_at=0 WHERE id=?").run(quoted.body.quote.id);
  const count = notes().length;
  for (let i = 0; i < 2; i++) assert.equal((await api("POST", "/api/me/crypto/confirm", a.token, { quoteId: quoted.body.quote.id })).status, 400);
  check("definitive failed confirmations are notified once", notes().length === count + 1 && notes().some(n => n.title === "Crypto purchase failed"));
  const withdrawal = { asset: "USDC", amount: "1", network: "Ethereum", address: "0x000000000000000000000000000000000000dead", requestKey: randomUUID() };
  const beforeWithdraw = notes().length;
  const recorded = await api("POST", "/api/me/crypto-withdrawals", a.token, withdrawal); assert.equal(recorded.status, 201);
  await api("POST", "/api/me/crypto-withdrawals", a.token, withdrawal);
  check("a withdrawal request creates one honest recorded notification", notes().length === beforeWithdraw + 1 && notes().some(n => n.title === "Crypto withdrawal recorded" && n.detail.includes("no blockchain transaction has been broadcast")));
  const failed = { ...withdrawal, amount: "999999", requestKey: randomUUID() };
  await api("POST", "/api/me/crypto-withdrawals", a.token, failed); await api("POST", "/api/me/crypto-withdrawals", a.token, failed);
  check("insufficient withdrawal notifies failure without fake success", notes().length === beforeWithdraw + 2 && notes().some(n => n.title === "Crypto withdrawal failed"));
  check("crypto notifications remain owner-scoped", !(await api("GET", "/api/me/notifications", b.token)).body.notifications.some((n: any) => n.type === "crypto"));
  for (const activity of CRYPTO_ACTIVITIES) for (const status of CRYPTO_STATUSES) {
    const data: CryptoNotification = { activity, status, asset: "BTC", quantity: "0.001", reference: "<script>alert(1)</script>", occurredAt: Date.now(), settlement: "account" };
    const mail = buildCryptoEmail(data, "https://app.veyra.com");
    assert.ok(mail.subject.includes(status)); assert.ok(mail.html.includes("&lt;script&gt;")); assert.ok(!mail.html.includes("<script>")); assert.ok(mail.text.includes("/#/app/assets"));
  }
  check("all 30 activity/status templates escape data and link to crypto activity", true);
  const invalid: CryptoNotification = { activity: "withdrawal", status: "completed", asset: "BTC", quantity: "1", reference: "unsafe", occurredAt: 1, settlement: "request" };
  assert.throws(() => cryptoNotificationContent(invalid)); assert.throws(() => cryptoNotificationContent({ ...invalid, settlement: "blockchain" }));
  check("unexecuted requests cannot use confirmed/completed wording", true);
  const beforeInvalid = notes().length; sendCryptoNotification(db, a.id, invalid);
  check("invalid provider success emits no notification", notes().length === beforeInvalid);
  const icons = ASSETS.map(a => assetIcon(a.code));
  check("all 24 supported assets have unique local images", new Set(icons).size === 24 && icons.every(path => path.startsWith("/images/crypto/")));
  check("asset images have distinct contents, not copied placeholders", new Set(icons.map(path => createHash("sha256").update(readFileSync(`public${path}`)).digest("hex"))).size === 24);
  const beforeReferenceBalance = db.prepare("SELECT balance_cents FROM accounts WHERE user_id=?").get(a.id)!.balance_cents;
  const referenceBody = { bankName: "Owner Bank", accountName: "Household checking", accountType: "Checking", accountNumber: "123456789012", ownershipConfirmed: true, requestKey: randomUUID() };
  const submitReference = (body = referenceBody, token = a.token) => api("POST", "/api/me/external-accounts", token, body);
  check("account references require authentication", (await api("POST", "/api/me/external-accounts", undefined, referenceBody)).status === 401);
  check("client cannot self-verify an external account", (await submitReference({ ...referenceBody, status: "verified" } as any)).status === 400);
  check("last four digits alone are rejected", (await submitReference({ ...referenceBody, accountNumber: undefined, last4: "6789" } as any)).status === 400);
  check("full external account numbers are accepted", (await submitReference({ ...referenceBody, accountNumber: "555123456789", requestKey: randomUUID() } as any)).status === 201);
  const pendingReference = await submitReference(); const referenceId = pendingReference.body.account.id;
  check("owner can submit a pending account reference without fabricating a bank link", pendingReference.status === 201 && pendingReference.body.account.status === "pending" && pendingReference.body.account.verification_kind === "staff_reference");
  check("request retry returns the same reference", (await submitReference()).body.account.id === referenceId);
  check("duplicate account reference is refused with a new key", (await submitReference({ ...referenceBody, requestKey: randomUUID() })).status === 400);
  check("pending references cannot fund an account", !(await funding()).methods.some((m: any) => m.linkedAccountId === referenceId));
  const reviewPath = `/api/admin/members/${a.id}/external-accounts/${referenceId}/review`;
  const approval = { decision: "approve", ownershipVerified: true, note: "Ownership independently verified; evidence reference A-209." };
  check("owner cannot approve their own account reference", (await api("POST", reviewPath, a.token, approval)).status === 403);
  check("review cannot cross account ownership", (await api("POST", `/api/admin/members/${b.id}/external-accounts/${referenceId}/review`, admin, approval)).status === 400);
  check("staff must explicitly attest independent ownership verification", (await api("POST", reviewPath, admin, { ...approval, ownershipVerified: false })).status === 400);
  const beforeReview = (db.prepare("SELECT COUNT(*) AS n FROM audit_log WHERE action='external_account.review'").get() as any).n;
  check("staff can approve an account reference", (await api("POST", reviewPath, admin, approval)).status === 200);
  await api("POST", reviewPath, admin, approval);
  check("replaying staff approval does not duplicate the audit event", (db.prepare("SELECT COUNT(*) AS n FROM audit_log WHERE action='external_account.review'").get() as any).n === beforeReview + 1);
  check("saving and approving a reference never moves money", db.prepare("SELECT balance_cents FROM accounts WHERE user_id=?").get(a.id)!.balance_cents === beforeReferenceBalance);
  const referenceMethod = (await funding()).methods.find((m: any) => m.linkedAccountId === referenceId);
  check("approved reference appears in dropdown with honest scope", referenceMethod?.label.includes("Account reference"));
  check("approved reference supports only the existing explicit internal credit", (await deposit(referenceMethod.id)).status === 201);
  check("another owner cannot fund from an approved reference", (await deposit(referenceMethod.id,randomUUID(),b.token)).status === 400);
  const rejectedReference = await submitReference({ ...referenceBody, accountNumber: "444433332222", requestKey: randomUUID() });
  await api("POST", `/api/admin/members/${a.id}/external-accounts/${rejectedReference.body.account.id}/review`, admin, { decision: "reject", note: "Unable to independently verify ownership of this account." });
  check("declined references stay out of funding choices", !(await funding()).methods.some((m: any) => m.linkedAccountId === rejectedReference.body.account.id));
  console.log(`\n${checks} crypto/funding polish checks passed.`);
} finally { server.closeAllConnections(); await new Promise<void>(r => server.close(() => r())); prices.closeAllConnections(); await new Promise<void>(r => prices.close(() => r())); db.close(); }
