import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { randomUUID } from 'node:crypto';
import { createApp } from '../src/app.js';
import { applicationFor } from './fixtures.js';
import { recentMail } from '../src/mail.js';
import { setRolePermissions } from '../src/rbac.js';

process.env.NODE_ENV='development';process.env.MAIL_PROVIDER='off';process.env.RECAPTCHA_SITE_KEY='';process.env.FIREBASE_PROJECT_ID='';
process.env.ADMIN_EMAIL='customer-admin@veyra.test';process.env.ADMIN_PASSWORD='Customer-Admin-Test-2026!';
const {app,db}=createApp(':memory:');const server=createServer(app);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
const api=async(method:string,path:string,token?:string,body?:unknown)=>{const r=await fetch(base+path,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,json:await r.json() as any};};
let checks=0;const check=(label:string,ok:unknown)=>{assert.ok(ok,label);checks++;console.log(`✓ ${label}`);};
try{
 const admin=(await api('POST','/api/auth/login',undefined,{email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD})).json.token;
 async function member(name:string){const r=await api('POST','/api/auth/register',undefined,{name,email:`${name}@veyra.test`,password:'Customer-Test-2026!',accountType:'personal',profile:applicationFor('personal',name)});assert.equal(r.status,201);await api('POST',`/api/admin/kyc/${r.json.user.id}/decision`,admin,{decision:'approved'});return {id:r.json.user.id,token:r.json.token,email:`${name}@veyra.test`};}
 const alice=await member('Alice'),bob=await member('Bob'),staff=await member('Operator'),teammate=await member('Teammate');
 db.prepare("UPDATE users SET role='support' WHERE id=?").run(staff.id);db.prepare("UPDATE users SET team_owner_id=? WHERE id=?").run(alice.id,teammate.id);
 const profile=await api('GET',`/api/admin/members/${alice.id}`,admin);
 check('dedicated customer data returns bank metadata and live edit permissions',profile.status===200&&profile.json.member.bankName&&profile.json.permissions.includes('accounts.edit_number'));
 check('customer monetary values retain the API cents/amount shape',profile.json.member.balance.cents===0&&profile.json.member.balance.amount==='0.00');
 check('customer data reports delivery as unconfigured when mail is off',profile.json.emailDeliveryConfigured===false);
 check('members cannot read a dedicated admin customer page API',(await api('GET',`/api/admin/members/${alice.id}`,alice.token)).status===403);
 check('missing customers return an explicit not found',(await api('GET','/api/admin/members/missing',admin)).status===404);
 check('staff cannot be read through member profile endpoints',(await api('GET',`/api/admin/members/${staff.id}`,admin)).status===404);
 setRolePermissions(db,'support',['customers.view']);
 const limited=(await api('GET',`/api/admin/members/${alice.id}`,staff.token)).json;
 check('customer-only roles do not receive bank fields, balances, identity or transactions',limited.member.balance===undefined&&limited.member.accountNumber===undefined&&limited.identity===null&&limited.transactions.length===0);
 const previewPath='/api/admin/accounts/bulk-preview',applyPath='/api/admin/accounts/bulk-apply';
 const draft={scope:'selected',userIds:[alice.id,bob.id],patch:{bankName:'Shared Settlement Bank',routingNumber:'021000021',bankAccountType:'Savings'},reason:'Verified receiving-bank metadata update'};
 check('bulk preview requires authentication',(await api('POST',previewPath,undefined,draft)).status===401);
 check('member bulk edits are forbidden',(await api('POST',previewPath,alice.token,draft)).status===403);
 check('read-only staff bulk edits are forbidden',(await api('POST',previewPath,staff.token,draft)).status===403);
 check('empty fields cannot be applied',(await api('POST',previewPath,admin,{...draft,patch:{bankName:''}})).status===400);
 check('invalid routing checksum is refused',(await api('POST',previewPath,admin,{...draft,patch:{routingNumber:'021000022'}})).status===400);
 check('account numbers cannot be bulk changed',(await api('POST',previewPath,admin,{...draft,patch:{accountNumber:'123456789'}})).status===400);
 check('Personal/Business cannot be bulk changed',(await api('POST',previewPath,admin,{...draft,patch:{accountType:'personal'}})).status===400);
 check('inherited property names are refused',(await api('POST',previewPath,admin,{...draft,patch:{toString:'bad'}})).status===400);
 check('an audit reason is mandatory',(await api('POST',previewPath,admin,{...draft,reason:''})).status===400);
 check('empty selections are refused',(await api('POST',previewPath,admin,{...draft,userIds:[]})).status===400);
 check('duplicate selections are refused',(await api('POST',previewPath,admin,{...draft,userIds:[alice.id,alice.id]})).status===400);
 check('staff accounts cannot be selected',(await api('POST',previewPath,admin,{...draft,userIds:[alice.id,staff.id]})).status===400);
 check('teammate logins cannot be selected',(await api('POST',previewPath,admin,{...draft,userIds:[teammate.id]})).status===400);
 const bankRows=()=>db.prepare('SELECT user_id,account_number,balance_cents,bank_name,routing_number,bank_account_type FROM accounts ORDER BY user_id').all();
 const before=bankRows();const review=await api('POST',previewPath,admin,draft);assert.equal(review.status,200);
 check('review masks account numbers and does not mutate any bank details',review.json.rows.length===2&&review.json.rows.every((r:any)=>r.accountLast4.length===4&&!('accountNumber' in r))&&JSON.stringify(before)===JSON.stringify(bankRows()));
 const apply={previewId:review.json.previewId,confirmation:'UPDATE 2'};
 check('confirmation must match the reviewed count',(await api('POST',applyPath,admin,{...apply,confirmation:'UPDATE 1'})).status===400);
 setRolePermissions(db,'support',['accounts.edit_number']);
 check('another authorized operator cannot apply someone else’s review',(await api('POST',applyPath,staff.token,apply)).status===400);
 const applied=await api('POST',applyPath,admin,apply);
 check('selected bank changes apply to the exact reviewed owners',applied.status===200&&applied.json.changedCount===2);
 check('bulk preserves every account number and every balance',JSON.stringify(before.map((r:any)=>[r.user_id,r.account_number,r.balance_cents]))===JSON.stringify(bankRows().map((r:any)=>[r.user_id,r.account_number,r.balance_cents])));
 check('staff and teammate bank data stay unchanged',bankRows().filter((r:any)=>[staff.id,teammate.id].includes(r.user_id)).every((r:any)=>r.bank_name!=='Shared Settlement Bank'));
 const auditCount=()=>Number((db.prepare("SELECT COUNT(*) AS n FROM audit_log WHERE action LIKE 'account.bulk_%'").get() as any).n);
 const auditBefore=auditCount();const repeated=await api('POST',applyPath,admin,apply);
 check('retrying an applied review returns the same result without duplicate audit',repeated.status===200&&repeated.json.replayed===true&&auditBefore===auditCount());
 check('one per-member audit and one batch audit are recorded',auditBefore===3);
 const stale=await api('POST',previewPath,admin,{...draft,patch:{bankName:'Stale change'}});
 db.prepare('UPDATE accounts SET bank_name=? WHERE user_id=?').run('Concurrent correction',alice.id);
 check('concurrent metadata edits reject the entire batch',(await api('POST',applyPath,admin,{previewId:stale.json.previewId,confirmation:'UPDATE 2'})).status===400&&(db.prepare('SELECT bank_name FROM accounts WHERE user_id=?').get(bob.id) as any).bank_name==='Shared Settlement Bank');
 const expired=await api('POST',previewPath,admin,draft);db.prepare('UPDATE account_bulk_previews SET expires_at=0 WHERE id=?').run(expired.json.previewId);
 check('expired reviews cannot be applied',(await api('POST',applyPath,admin,{previewId:expired.json.previewId,confirmation:'UPDATE 2'})).status===400);
 const all=await api('POST',previewPath,admin,{scope:'all',patch:{bankName:'All Owners Bank'},reason:'Shared-bank update'});
 check('all scope includes owners, not staff or teammates',all.json.count===2&&all.json.rows.every((r:any)=>[alice.id,bob.id].includes(r.userId)));
 const later=await member('Later');
 check('all scope is frozen at preview time',(await api('POST',applyPath,admin,{previewId:all.json.previewId,confirmation:'UPDATE 2'})).status===200&&(db.prepare('SELECT bank_name FROM accounts WHERE user_id=?').get(later.id) as any).bank_name!=='All Owners Bank');
 const atomic=await api('POST',previewPath,admin,{...draft,patch:{bankName:'Rollback test'}});
 db.exec("CREATE TEMP TRIGGER fail_bulk_audit BEFORE INSERT ON audit_log WHEN NEW.action='account.bulk_summary' BEGIN SELECT RAISE(ABORT,'fixture audit failure'); END;");
 check('an audit failure rolls back the whole batch',(await api('POST',applyPath,admin,{previewId:atomic.json.previewId,confirmation:'UPDATE 2'})).status>=400&&bankRows().filter((r:any)=>[alice.id,bob.id].includes(r.user_id)).every((r:any)=>r.bank_name==='All Owners Bank'));
 db.exec('DROP TRIGGER fail_bulk_audit');
 const revoked=await api('POST',previewPath,staff.token,{...draft,patch:{bankName:'Revoked role change'}});setRolePermissions(db,'support',['customers.view']);
 check('revoked bulk permissions take effect before applying',(await api('POST',applyPath,staff.token,{previewId:revoked.json.previewId,confirmation:'UPDATE 2'})).status===403);

 recentMail.length=0;
 await api('POST',`/api/admin/members/${alice.id}/adjust`,admin,{direction:'credit',amount:1000,memo:'Synthetic notification fixture'});
 const outgoing=await api('POST','/api/me/transfers',alice.token,{amount:25,counterparty:'<img src=x onerror=alert(1)>',method:'Zelle'});
 const sent=recentMail.find(m=>m.tag==='zelle-outgoing-recorded');
 check('outgoing Zelle ledger activity generates an account-owner email',outgoing.status===201&&sent?.to===alice.email&&sent.text.includes(outgoing.json.result.reference));
 check('outgoing emails do not assert recipient settlement',sent?.text.includes('not confirmation that a payment was sent through Zelle'));
 check('counterparty HTML is escaped',sent?.html.includes('&lt;img src=x')&&!sent.html.includes('<img src=x'));
 const accountNumber=(db.prepare('SELECT account_number FROM accounts WHERE user_id=?').get(alice.id) as any).account_number;
 check('emails contain only the account suffix',sent?.text.includes(`•••• ${accountNumber.slice(-4)}`)&&!sent.text.includes(accountNumber));
 check('emails link to the actual hash-routed member app',sent?.html.includes('/#/app/transactions'));
 let count=recentMail.length;await api('POST','/api/me/transfers',alice.token,{amount:100000,counterparty:'No balance',method:'Zelle'});
 check('failed outgoing transfers send no notification',recentMail.length===count);
 await api('POST','/api/me/transfers',alice.token,{amount:1,counterparty:'ACH fixture',method:'ACH'});
 check('non-Zelle transfers send no Zelle notification',recentMail.length===count);
 const setup=await api('PUT',`/api/admin/members/${alice.id}/funding`,admin,{methods:[{kind:'zelle',label:'Zelle fixture',instructions:'Synthetic receiving details; do not send money.',recipient:'Alice',recipientContact:'alice@recipient.test',enabled:true}]});
 const payload={amount:40,methodId:setup.json.methods.find((m:any)=>m.enabled).id,requestKey:randomUUID()};
 const pending=await api('POST','/api/me/deposits',alice.token,payload);
 const pendingMail=recentMail.find(m=>m.tag==='zelle-incoming-pending');
 check('incoming pending emails do not claim available funds',pending.status===201&&pendingMail?.to===alice.email&&pendingMail.text.includes('No funds have been confirmed or credited'));
 count=recentMail.length;await api('POST','/api/me/deposits',alice.token,payload);
 check('replaying a funding request does not duplicate the pending email',recentMail.length===count);
 const reviewUrl=`/api/admin/members/${alice.id}/funding/${pending.json.request.id}/review`;
 await api('POST',reviewUrl,alice.token,{decision:'confirmed',evidence:'Unauthorized'});
 check('unauthorized incoming confirmation sends no email',recentMail.length===count);
 await api('POST',reviewUrl,admin,{decision:'confirmed',evidence:'Independent synthetic receipt check'});
 const received=recentMail.find(m=>m.tag==='zelle-incoming-confirmed');
 check('confirmed incoming credit generates the matching owner email',received?.text.includes(pending.json.request.reference)&&received.to===alice.email&&received.text.includes('staff confirmed receipt'));
 count=recentMail.length;await api('POST',reviewUrl,admin,{decision:'confirmed',evidence:'Independent synthetic receipt check'});
 check('replayed confirmation does not duplicate the credit email',recentMail.length===count);
 const pending2=await api('POST','/api/me/deposits',alice.token,{...payload,requestKey:randomUUID()});
 await api('POST',`/api/admin/members/${alice.id}/funding/${pending2.json.request.id}/review`,admin,{decision:'rejected',evidence:'No incoming receipt located'});
 check('declined incoming requests get a non-credit notification',recentMail.some(m=>m.tag==='zelle-incoming-rejected'&&m.text.includes('No funds were credited')));
 check('Zelle notices go only to the owner, never a configured recipient',recentMail.filter(m=>m.tag.startsWith('zelle-')).every(m=>m.to===alice.email));
 // Mail failure cannot turn a committed payment into a reported decline.
 const actualFetch=globalThis.fetch;process.env.MAIL_PROVIDER='resend';process.env.MAIL_API_KEY='test-only';
 let attempts=0;globalThis.fetch=(async(input,init)=>{if(String(input).startsWith('https://api.resend.com/')){attempts++;return new Response('Synthetic outage',{status:503});}return actualFetch(input,init);}) as typeof fetch;
 try{const result=await api('POST','/api/me/transfers',alice.token,{amount:1,counterparty:'Provider failure fixture',method:'Zelle'});check('email provider failure never rolls back a committed ledger transfer',result.status===201&&attempts===1);}finally{globalThis.fetch=actualFetch;process.env.MAIL_PROVIDER='off';process.env.MAIL_API_KEY='';}
 console.log(`\nALL CUSTOMER ADMIN TESTS PASSED (${checks} checks)`);
}finally{await new Promise<void>(r=>server.close(()=>r()));db.close();}
