import assert from "node:assert/strict";
import { createServer } from "node:http";
import { randomUUID } from "node:crypto";
import { createApp } from "../src/app.js";
import { applicationFor } from "./fixtures.js";
import { createPriceFixture } from "./price-fixture.js";
import { validWallet } from "../src/banking.js";
import { FUNDING_OPTIONS } from "../../shared/funding.js";
import { testFundingMigration } from "./test-funding-migration.js";
import { ASSETS } from "../../shared/catalog.js";

process.env.NODE_ENV="development";
process.env.MAIL_PROVIDER="off";
process.env.ADMIN_EMAIL="banking-admin@veyra.test";process.env.ADMIN_PASSWORD="banking-test-password";
process.env.RECAPTCHA_SITE_KEY=""; process.env.FIREBASE_PROJECT_ID=""; process.env.CRYPTO_TRADING_ENABLED="1";
const prices=createPriceFixture(); await new Promise<void>(r=>prices.listen(0,"127.0.0.1",r));
process.env.CRYPTO_PRICES_URL=`http://127.0.0.1:${(prices.address() as {port:number}).port}`;
const {app,db}=createApp(":memory:");const server=createServer(app);await new Promise<void>(r=>server.listen(0,"127.0.0.1",r));
const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
const api=async(method:string,path:string,token?:string,body?:unknown)=>{const r=await fetch(base+path,{method,headers:{"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,json:await r.json() as any};};
let checks=0; const check=(name:string,value:unknown)=>{assert.ok(value,name);checks++;console.log(`✓ ${name}`);};
try {
 const admin=(await api("POST","/api/auth/login",undefined,{email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD})).json.token;
 const register=async(type:"personal"|"business",name:string)=>{
  const r=await api("POST","/api/auth/register",undefined,{name,email:`${name}@veyra.test`,password:"banking-member-password",accountType:type,business:type==='business'?`${name} Ltd`:"",profile:applicationFor(type,name,`${name} Ltd`)});
  assert.equal(r.status,201,JSON.stringify(r.json));await api("POST",`/api/admin/kyc/${r.json.user.id}/decision`,admin,{decision:"approved"});return {token:r.json.token as string,id:r.json.user.id as string};
 };
 const alice=await register("personal","Alice"),bob=await register("business","Bob");
 const state=async(token=alice.token)=>(await api("GET","/api/me/state",token)).json.account;
 const baseAccount=(await api("GET",`/api/admin/members/${alice.id}/account-details`,admin)).json.account;
 const changedAccount={...baseAccount,accountNumber:"12345678901234",routingNumber:"021000021",bankName:"Test Settlement Bank",bankAccountType:"Savings",reason:"Verified synthetic account correction"};
 check("members cannot edit their own bank identity",(await api("PATCH",`/api/admin/members/${alice.id}/account-details`,alice.token,changedAccount)).status===403);
 check("admin can edit all bank metadata",(await api("PATCH",`/api/admin/members/${alice.id}/account-details`,admin,changedAccount)).status===200);
 const bank=(await state()).bankDetails;
 check("member state reflects routing, account, bank and savings designation",bank.accountNumber===changedAccount.accountNumber&&bank.routingNumber===changedAccount.routingNumber&&bank.bankName===changedAccount.bankName&&bank.accountType==='Personal savings');
 check("invalid ABA checksum fails",(await api("PATCH",`/api/admin/members/${alice.id}/account-details`,admin,{...changedAccount,routingNumber:"021000022"})).status===400);
 check("duplicate account number cannot cross owners",(await api("PATCH",`/api/admin/members/${bob.id}/account-details`,admin,{...changedAccount,accountType:"business",business:"Bob Ltd"})).status===400);
 check("bank edits are audited",!!db.prepare("SELECT 1 FROM audit_log WHERE action='account.details'").get());
 check("admin can convert an owner to business",(await api("PATCH",`/api/admin/members/${alice.id}/account-details`,admin,{...changedAccount,accountType:"business",business:"Alice Ltd"})).status===200);
 const invitation=await api("POST","/api/me/team",alice.token,{name:"Teammate",email:"teammate@veyra.test",role:"Member",monthlyLimit:100});assert.equal(invitation.status,201);
 check("conversion to personal refuses active/pending team access",(await api("PATCH",`/api/admin/members/${alice.id}/account-details`,admin,changedAccount)).status===400);
 await api("DELETE",`/api/me/team/${invitation.json.member.id}`,alice.token);
 check("conversion works after removing the invitation",(await api("PATCH",`/api/admin/members/${alice.id}/account-details`,admin,changedAccount)).status===200);
 check("no synthetic sources are installed by default",(await api("GET","/api/me/funding",alice.token)).json.methods.length===0);
 const method={label:"Verified inbound wire",kind:"wire",instructions:"Synthetic instructions. Contact operations to confirm receipt.",recipient:"Alice",bankName:"Test Bank",routingNumber:"021000021",accountNumber:"123456789012",enabled:true};
 check("member cannot configure funding routes",(await api("PUT",`/api/admin/members/${alice.id}/funding`,alice.token,{methods:[method]})).status===403);
 const setup=await api("PUT",`/api/admin/members/${alice.id}/funding`,admin,{methods:[method]});assert.equal(setup.status,200,JSON.stringify(setup.json));const methodId=setup.json.methods[0].id;
 check("funding instructions are scoped to a single member",(await api("GET","/api/me/funding",alice.token)).json.methods[0].label===method.label&&(await api("GET","/api/me/funding",bob.token)).json.methods.length===0);
 const payload={amount:"1000.00",methodId,requestKey:randomUUID(),note:"Fixture inbound proof"};
 check("another member cannot use that funding method",(await api("POST","/api/me/deposits",bob.token,payload)).status===400);
 check("legacy source text cannot self-credit money",(await api("POST","/api/me/deposits",alice.token,{amount:1000,source:"Invented"})).status===400&&(await state()).balance===0);
 const [r1,r2]=await Promise.all([api("POST","/api/me/deposits",alice.token,payload),api("POST","/api/me/deposits",alice.token,payload)]);
 check("concurrent duplicate deposit requests return the same pending record",r1.status===201&&r1.json.request.id===r2.json.request.id&&r1.json.request.status==='pending');
 check("pending request cannot increase a balance or ledger",(await state()).balance===0&&(await state()).transactions.length===0);
 check("reused key with a changed amount is refused",(await api("POST","/api/me/deposits",alice.token,{...payload,amount:1001})).status===400);
 const reviewPath=`/api/admin/members/${alice.id}/funding/${r1.json.request.id}/review`;
 check("member cannot confirm their own funds",(await api("POST",reviewPath,alice.token,{decision:"confirmed",evidence:"Fake"})).status===403);
 check("admin confirmation requires evidence",(await api("POST",reviewPath,admin,{decision:"confirmed",evidence:""})).status===400);
 const review={decision:"confirmed",evidence:"Independent synthetic settlement confirmation"};
 const confirmed=await Promise.all([api("POST",reviewPath,admin,review),api("POST",reviewPath,admin,review)]);
 check("confirmation credits exactly once under replay",confirmed.every(r=>r.status===200)&&(await state()).balance===1000&&(await state()).transactions.length===1);
 check("contradictory review is refused",(await api("POST",reviewPath,admin,{decision:"rejected",evidence:"Later"})).status===400);
 const next=await api("POST","/api/me/deposits",alice.token,{...payload,requestKey:randomUUID(),amount:10});
 await api("POST",`/api/admin/members/${alice.id}/funding/${next.json.request.id}/review`,admin,{decision:"rejected",evidence:"No receipt located"});
 check("rejection makes no financial entry",(await state()).balance===1000&&(await state()).transactions.length===1);
 await api("PUT",`/api/admin/members/${alice.id}/funding`,admin,{methods:[{...method,id:methodId,enabled:false}]});
 check("disabled sources disappear and cannot be used",(await api("GET","/api/me/funding",alice.token)).json.methods.length===0&&(await api("POST","/api/me/deposits",alice.token,{...payload,requestKey:randomUUID()})).status===400);
 // Upgrade an actual pre-change schema, including prior confirmed/rejected records.
 testFundingMigration(db, check);
 const availableKinds=FUNDING_OPTIONS.map(o=>({label:o.label,kind:o.kind,instructions:"Synthetic-only setup. Do not send real funds.",recipient:"Alice",recipientContact:o.kind==='zelle'?'alice@example.test':'',enabled:true}));
 const fundPath=`/api/admin/members/${alice.id}/funding`;
 const newSetup=await api("PUT",fundPath,admin,{methods:availableKinds});
 check("all eight funding kinds can be configured per member",newSetup.status===200&&availableKinds.every(m=>newSetup.json.methods.some((r:any)=>r.kind===m.kind&&r.enabled)));
 check("unknown funding kinds are rejected",(await api("PUT",fundPath,admin,{methods:[{...method,kind:"invented"}]})).status===400);
 check("Zelle requires an enrolled email or US phone",(await api("PUT",fundPath,admin,{methods:[{...availableKinds[2],recipientContact:"not-a-contact"}]})).status===400);
 check("enabled Zelle requires a recipient name",(await api("PUT",fundPath,admin,{methods:[{...availableKinds[2],recipient:""}]})).status===400);
 check("bank details cannot be mistaken for Zelle contact details",(await api("PUT",fundPath,admin,{methods:[{...availableKinds[2],accountNumber:"1234567890"}]})).status===400);
 check("full card numbers cannot be stored in card fields",(await api("PUT",fundPath,admin,{methods:[{...availableKinds[1],accountNumber:"4242424242424242"}]})).status===400);
 check("unconnected ACH setup does not collect external bank details",(await api("PUT",fundPath,admin,{methods:[{...availableKinds[0],routingNumber:"021000021",accountNumber:"1234567890"}]})).status===400);
 const configured=(await api("GET","/api/me/funding",alice.token)).json.methods;
 const beforeFunding=(await state()).balance;
 for(const kind of ['ach','card']) {
   const pendingBefore=db.prepare("SELECT COUNT(*) AS n FROM funding_requests").get() as {n:number};
   const attempted=await api("POST","/api/me/deposits",alice.token,{amount:25,methodId:configured.find((m:any)=>m.kind===kind).id,requestKey:randomUUID()});
   check(`${kind} cannot initiate deposits through a forged request`,attempted.status===400&&attempted.json.error.includes("provider activation"));
   check(`${kind} creates no request or credit`,(db.prepare("SELECT COUNT(*) AS n FROM funding_requests").get() as {n:number}).n===pendingBefore.n&&(await state()).balance===beforeFunding);
 }
 for(const kind of ['zelle','direct_deposit']) {
   const submitted=await api("POST","/api/me/deposits",alice.token,{amount:25,methodId:configured.find((m:any)=>m.kind===kind).id,requestKey:randomUUID()});
   check(`${kind} creates only a pending manual request`,submitted.status===201&&submitted.json.request.status==='pending'&&(await state()).balance===beforeFunding);
   if(kind==='zelle') check("Zelle recipient contact is snapshotted",JSON.parse(submitted.json.request.method_snapshot).recipient_contact==='alice@example.test');
 }
 const zelle=configured.find((m:any)=>m.kind==='zelle');
 check("other members never see the Zelle recipient",!(await api("GET","/api/me/funding",bob.token)).json.methods.some((m:any)=>m.recipient_contact));
 check("other members cannot submit against Zelle instructions",(await api("POST","/api/me/deposits",bob.token,{amount:25,methodId:zelle.id,requestKey:randomUUID()})).status===400);
 check("US phone contacts are accepted for Zelle instructions",(await api("PUT",fundPath,admin,{methods:[{...availableKinds[2],id:zelle.id,recipientContact:'+1 (212) 555-0123'}]})).status===200);
 check("personal transfer category is optional",(await api("POST","/api/me/transfers",alice.token,{amount:1,counterparty:"Fixture"})).status===201&&(await state()).transactions[0].category==='Uncategorized');
 check("business transfer category is required",(await api("POST","/api/me/transfers",bob.token,{amount:1,counterparty:"Fixture"})).status===400);
 let holdings=(await api("GET","/api/me/holdings",alice.token)).json;
 check("24 explicit supported assets with accurate decimals",holdings.holdings.length===ASSETS.length&&ASSETS.length===24&&holdings.holdings.find((h:any)=>h.asset==='NEAR').decimals===24);
 const markets=(await api("GET","/api/me/markets",alice.token)).json;
 check("market and holdings quotes agree for each quoted supported asset",markets.markets.every((m:any)=>!m.tradeable||m.priceUsd===holdings.holdings.find((h:any)=>h.asset===m.code).priceUsd));
 check("changed displayed quote prevents a trade",(await api("POST","/api/me/holdings/trade",alice.token,{asset:"USDC",side:"buy",amount:"100",expectedPriceUsd:"2.00"})).status===409);
 assert.equal((await api("POST","/api/me/holdings/trade",alice.token,{asset:"USDC",side:"buy",amount:"100",expectedPriceUsd:"1.00"})).status,201);
 const withdrawal={asset:"USDC",network:"Ethereum",amount:"25.123456",address:"0x1111111111111111111111111111111111111111",requestKey:randomUUID()};
 check("unsupported/mismatched network is rejected",(await api("POST","/api/me/crypto-withdrawals",alice.token,{...withdrawal,network:"Solana"})).status===400);
 check("excess unit precision is rejected rather than rounded",(await api("POST","/api/me/crypto-withdrawals",alice.token,{...withdrawal,amount:"0.1234567"})).status===400);
 check("bad wallet address is rejected",(await api("POST","/api/me/crypto-withdrawals",alice.token,{...withdrawal,address:"wrong"})).status===400);
 const beforeWithdraw=await state();
 const [w1,w2]=await Promise.all([api("POST","/api/me/crypto-withdrawals",alice.token,withdrawal),api("POST","/api/me/crypto-withdrawals",alice.token,withdrawal)]);
 check("duplicate withdrawal reserves only once",w1.status===201&&w1.json.withdrawal.id===w2.json.withdrawal.id);
 holdings=(await api("GET","/api/me/holdings",alice.token)).json;let usdc=holdings.holdings.find((h:any)=>h.asset==='USDC');
 check("pending units remain in total holdings but not available units",usdc.quantity==='74.876544'&&usdc.reservedQuantity==='25.123456'&&usdc.totalQuantity==='100'&&holdings.totalUsd==='100.00');
 check("withdrawal is only pending and has no invented transaction hash",w1.json.withdrawal.status==='pending'&&!('txHash' in w1.json.withdrawal));
 check("withdrawal never changes checking or creates a fiat transfer",(await state()).balance===beforeWithdraw.balance&&(await state()).transactions.length===beforeWithdraw.transactions.length);
 check("reserved units cannot be sold",(await api("POST","/api/me/holdings/trade",alice.token,{asset:"USDC",side:"sell",amount:"100"})).status===400);
 check("reserved units cannot be requested again",(await api("POST","/api/me/crypto-withdrawals",alice.token,{...withdrawal,amount:"80",requestKey:randomUUID()})).status===400);
 check("another member cannot cancel the withdrawal",(await api("POST",`/api/me/crypto-withdrawals/${w1.json.withdrawal.id}/cancel`,bob.token)).status===400);
 check("other member cannot read the pending withdrawal",(await api("GET","/api/me/crypto-withdrawals",bob.token)).json.withdrawals.length===0);
 await Promise.all([api("POST",`/api/me/crypto-withdrawals/${w1.json.withdrawal.id}/cancel`,alice.token),api("POST",`/api/me/crypto-withdrawals/${w1.json.withdrawal.id}/cancel`,alice.token)]);
 usdc=(await api("GET","/api/me/holdings",alice.token)).json.holdings.find((h:any)=>h.asset==='USDC');
 check("cancellation restores exactly the reserved amount once",usdc.quantity==='100'&&usdc.reservedUnits==='0');
 process.env.CRYPTO_TRADING_ENABLED="0";
 check("production movement switch blocks withdrawal requests",(await api("POST","/api/me/crypto-withdrawals",alice.token,{...withdrawal,requestKey:randomUUID()})).status===503);
 process.env.CRYPTO_TRADING_ENABLED="1";
 check("Bitcoin mainnet checksum validation accepts a valid address",validWallet("Bitcoin","1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"));
 check("Bitcoin checksum and wrong-network addresses fail",!validWallet("Bitcoin","1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNb")&&!validWallet("Ethereum","1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"));
 console.log(`\nALL BANKING UPDATE TESTS PASSED (${checks} checks)`);
} finally {await new Promise<void>(r=>server.close(()=>r()));await new Promise<void>(r=>prices.close(()=>r()));db.close();}
